-- 01. Qual o total de receita gerada por clientes homens e mulheres?
-- 01. What is the total revenue generated by male vs. female customers?

SELECT
	gender,
	SUM(purchase_amount) AS revenue
FROM customer
GROUP BY gender;

-- 02. Quais clientes usaram um desconto mas ainda assim gastaram mais que o valor médio da compra?
-- 02. Which customers used a discount but still spent more than the average purchase amount?

SELECT
	customer_id,
	purchase_amount
FROM customer
WHERE discount_applied = 'yes'
	AND
	purchase_amount >= (
		SELECT
			AVG(purchase_amount) AS avg_purchase_amount
		FROM customer
		);
	
	