


--------------------------------
-- Autor: Miguel Santos
-- Data: 2025-11-30
--------------------------------

-- 01. Qual o total de receita gerada por clientes homens e mulheres?
-- 01. What is the total revenue generated by male vs. female customers?

SELECT
	gender,
	SUM(purchase_amount) AS revenue
FROM customer
GROUP BY gender;

-- 02. Quais clientes usaram um desconto mas ainda assim gastaram mais que o valor médio da compra?
-- 02. Which customers used a discount but still spent more than the average purchase amount?

SELECT
	COUNT(customer_id)
FROM customer
WHERE discount_applied = 'yes'
	AND
	purchase_amount >= (
		SELECT
			AVG(purchase_amount) AS avg_purchase_amount
		FROM customer
		);

-- 03. Qual o top 5 produtos com a média de taxa de revisão mais alta?
-- 03. Which are the top 5 products with the highest average review rating?

SELECT
	item_purchased,
	ROUND(AVG(review_rating::numeric), 2) AS avg_review_rating
FROM customer
GROUP BY item_purchased
ORDER BY avg_review_rating DESC
LIMIT 5;

-- 04. Qual a diferença dos valores médios de compra entre os fretes padrão e expresso?
-- 04. What is the difference in average purchase values ​​between standard and express shipping?

SELECT
	shipping_type,
	ROUND(AVG(purchase_amount), 2) AS avg_purchase_amount
FROM customer
GROUP BY shipping_type
ORDER BY avg_purchase_amount DESC;

-- 05. Clientes inscritos gastam mais? Qual a diferença da média do valor médio de compra entre inscritos e não-inscritos?
-- 05. Do registered customers spend more? What is the difference in average purchase value between registered and non-registered customers?

SELECT
	subscription_status,
	COUNT(customer_id) AS total_customers,
	ROUND(AVG(purchase_amount), 2) AS avg_spend,
	ROUND(SUM(purchase_amount), 2) AS total_revenue,
	ROUND((SUM(customer_id) * 100 / (SELECT SUM(customer_id) FROM customer)), 2) AS percentage_customers,
	ROUND((SUM(purchase_amount) * 100 / (SELECT SUM(purchase_amount) FROM customer)), 2) AS percentage_total_revenue
FROM customer
GROUP BY subscription_status
ORDER BY total_revenue, avg_spend DESC;

-- 06. Quais os 5 produtos possuem a maior porcentagem de vendas com aplicação de desconto?
-- 06. Which 5 products have the highest percentage of purchases with discount applied?

SELECT
	item_purchased,
	ROUND(100 * SUM(CASE WHEN discount_applied = 'yes' THEN 1 ELSE 0 END) / COUNT(*), 2) AS percentage
FROM customer
GROUP BY item_purchased
ORDER BY percentage DESC
LIMIT 5;

-- 07. Segmente os clientes em Novos, Recorrentes e Fiéis com base no número total de compras anteriores e mostre a contagem de cada segmento.
-- 07. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show show the count of each segment

WITH customer_type AS (
    SELECT customer_id,
           previous_purchases,
           CASE
               WHEN previous_purchases = 1 THEN 'New'
               WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
               ELSE 'Loyal'
           END AS customer_segment
    FROM customer
)
SELECT
    customer_segment,
    COUNT(*) AS count_customers,
    ROUND((COUNT(*) * 100.0 / (SELECT COUNT(*) FROM customer_type)), 2) AS percentage
FROM customer_type
GROUP BY customer_segment
ORDER BY count_customers ASC;


-- 08. Qual o top 3 produtos mais comprados em cada categoria?
-- 08. What are the top 3 most products purchased within each category?

WITH item_counts AS(
SELECT
	category,
	item_purchased,
	COUNT(customer_id) AS total_orders,
	ROW_NUMBER() OVER(PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
FROM customer
GROUP BY category, item_purchased
)
SELECT
	item_rank,
	category,
	item_purchased,
	total_orders
FROM item_counts
WHERE item_rank <= 3;

-- 09. Quais clientes são compradores repetitivos (mais que 5 compras anteriores) também estão inscritos?
-- 09. How many customers are repeat buyers (more than 5 previous purchases) also likely to subscribe?

SELECT
	subscription_status,
	COUNT(customer_id) AS repeat_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;

-- 10. Qual a porcentagem de participação na receita gerada por cada grupo de idade?
-- 10. What's the participation percentage revenue contribution of each age group?

SELECT
	age_group,
	SUM(purchase_amount) AS total_revenue,
	ROUND((SUM(purchase_amount) * 100 / (SELECT SUM(purchase_amount) FROM customer)), 2) AS percentage,
	ROUND(SUM(SUM(purchase_amount)) OVER (ORDER BY SUM(purchase_amount) DESC) * 100 / (SELECT SUM(purchase_amount) FROM customer), 2) AS cumulative_percentage
FROM customer
GROUP BY age_group
ORDER BY total_revenue DESC;

-- 11. Qual o método de pagamento preferido em funçao da faixa etaria?
-- 11. What is the preferred payment method depending on the age group?

WITH payment_preferred AS(
SELECT
	age_group,
	payment_method,
	COUNT(*) AS method_preferred,
	ROW_NUMBER() OVER(PARTITION BY age_group ORDER BY COUNT(*) DESC) AS rank
FROM customer
GROUP BY age_group, payment_method
)
SELECT
	age_group,
	payment_method	
FROM payment_preferred
WHERE rank = 1;

-- 12. Quais as top 3 localidades de cada região na receita total?
-- 12. Which top 3 locations each region in total revenue?

WITH region_rank AS(
SELECT
	region,
	location,
	SUM(purchase_amount) AS total_revenue,
	ROW_NUMBER() OVER(PARTITION BY region ORDER BY SUM(purchase_amount) DESC) AS location_rank
FROM customer
GROUP BY region, location
)
SELECT
	*
FROM region_rank
WHERE location_rank <= 1;

-- 13. Qual o top 3 item mais vendido de cada categoria em cada estação?
-- 13. Which top 3 item more purchased by each category and each season?

WITH season_purchase AS(
SELECT
	item_purchased,
	category,
	season,
	SUM(purchase_amount) AS total_revenue,
	ROW_NUMBER() OVER(PARTITION BY (category, season) ORDER BY SUM(purchase_amount) DESC) AS item_rank
FROM customer
GROUP BY item_purchased, category, season
)
SELECT
	*
FROM season_purchase
WHERE item_rank <= 3;

-- 14. Qual o item mais comprado em cada estação e a sua cor mais popular?
-- 14. What's the most purchased product in each season and its most popular color?

WITH most_popular AS(
SELECT
	item_purchased,
	season,
	color,
	COUNT(customer_id) AS count_sales,
	ROW_NUMBER() OVER(PARTITION BY (season) ORDER BY COUNT(customer_id) DESC) AS popular_rank
FROM customer
GROUP BY item_purchased, season, color
)
SELECT
	season,
	item_purchased,
    color,
	count_sales
FROM most_popular
WHERE popular_rank = 1;

-- 15. Qual o tamanho mais comprado de cada categoria por faixa etária?
-- 15. What's the most purchased size in each category by age group ?

WITH size_age AS(
SELECT
	category,
	size,
	age_group,
	COUNT(customer_id),
	ROW_NUMBER() OVER(PARTITION BY (category, age_group) ORDER BY COUNT(customer_id) DESC) AS popular_size_age
FROM customer
GROUP BY category, size, age_group
)
SELECT
	age_group,
	category,
	size
FROM size_age
WHERE popular_size_age = 1
ORDER BY age_group;

----------------------------------------